<?xml version="1.0" encoding="utf-8"?><Database Name="help4IT_MSCRM" Class="CRMDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CARAWAY.help4it.local;Initial Catalog=help4IT_MSCRM;User ID=help4base" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="help4IT_MSCRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FilteredAccount" Member="FilteredAccounts">
    <Type Name="FilteredAccount">
      <Column Name="accountcategorycode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accountcategorycodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountclassificationcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accountclassificationcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="accountnumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="accountratingcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accountratingcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address1_addressid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="address1_addresstypecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address1_addresstypecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address1_city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_county" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_freighttermscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address1_freighttermscodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address1_latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="address1_line1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address1_line2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address1_line3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address1_longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="address1_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address1_postalcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address1_postofficebox" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address1_primarycontactname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="address1_shippingmethodcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address1_shippingmethodcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address1_stateorprovince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1_upszone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="address1_utcoffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address2_addressid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="address2_addresstypecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address2_addresstypecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address2_city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_county" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_freighttermscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address2_freighttermscodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address2_latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="address2_line1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address2_line2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address2_line3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address2_longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="address2_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address2_postalcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address2_postofficebox" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address2_primarycontactname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="address2_shippingmethodcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address2_shippingmethodcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address2_stateorprovince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address2_upszone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="address2_utcoffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="aging30" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="aging30_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="aging60" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="aging60_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="aging90" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="aging90_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="businesstypecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="businesstypecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdbydsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createdbyname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="createdbyyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createdonutc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="creditlimit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="creditlimit_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="creditonhold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="creditonholdname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="customersizecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customersizecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="customertypecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customertypecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="defaultpricelevelid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="defaultpriceleveliddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="defaultpricelevelidname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="donotbulkemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotbulkemailname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotbulkpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotbulkpostalmailname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotemailname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotfax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotfaxname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotphone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotphonename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotpostalmailname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotsendmarketingmaterialname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="donotsendmm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="emailaddress1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="emailaddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="emailaddress3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="exchangerate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ftpsiteurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="importsequencenumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="industrycode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="industrycodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="isprivatename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="lastusedincampaign" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastusedincampaignutc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="marketcap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="marketcap_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="masteraccountiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masteraccountidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="masteraccountidyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="masterid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="merged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mergedname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbydsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="modifiedbyyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonutc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_24x7heavysupport" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="new_24x7heavysupportname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_24x7support" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="new_24x7supportname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_accountmanager" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_accountmanagername" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_accountscontact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="new_accountscontactid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="new_accountscontactiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_accountscontactidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_accountscontactidyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="new_activitythisfinancialyear" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="new_activitythisfinancialyearname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_customersatisfaction" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="new_customersatisfactiondsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_customersatisfactionname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_customersatisfactionsurveycontact" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="new_customersatisfactionyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="new_leadsource" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_leadsourcename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_marketingcontactid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="new_marketingcontactiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_marketingcontactidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_marketingcontactidyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="new_numberofserversmonitored" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="new_numberofsupportedusers" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="new_roadmap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="new_roadmapname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_scheduledvisitfrequency" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="new_seniortechnician" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_seniortechnicianname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_supportcontract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_supportcontractname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="new_technicalcontactid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="new_technicalcontactiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_technicalcontactidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_technicalcontactidyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="new_testtechnician" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="numberofemployees" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="originatingleadid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="originatingleadiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="originatingleadidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="originatingleadidyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="overriddencreatedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="overriddencreatedonutc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="owneriddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owneridname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="owneridtype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owneridyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ownershipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ownershipcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="owningbusinessunit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="owningteam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="owninguser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="parentaccountid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="parentaccountiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parentaccountidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="parentaccountidyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="participatesinworkflow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="participatesinworkflowname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="paymenttermscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="paymenttermscodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="preferredappointmentdaycode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredappointmentdaycodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="preferredappointmenttimecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredappointmenttimecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="preferredcontactmethodcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredcontactmethodcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="preferredequipmentid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="preferredequipmentiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredequipmentidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="preferredserviceid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="preferredserviceiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredserviceidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="preferredsystemuserid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="preferredsystemuseriddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="preferredsystemuseridname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="preferredsystemuseridyominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="primarycontactid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="primarycontactiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="primarycontactidname" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="primarycontactidyominame" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="revenue" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="revenue_base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="sharesoutstanding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shippingmethodcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shippingmethodcodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="sic" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statecodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="stockexchange" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="territorycode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="territorycodename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="territoryid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="territoryiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="territoryidname" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tickersymbol" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="timezoneruleversionnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="transactioncurrencyid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="transactioncurrencyiddsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="transactioncurrencyidname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="utcconversiontimezonecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="websiteurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="yominame" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="crm_moneyformatstring" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>