'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18010
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="HumanResources")>  _
Partial Public Class HRDataClassesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertEmployeeDetail(instance As EmployeeDetail)
    End Sub
  Partial Private Sub UpdateEmployeeDetail(instance As EmployeeDetail)
    End Sub
  Partial Private Sub DeleteEmployeeDetail(instance As EmployeeDetail)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("HumanResourcesConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EmployeeDetails() As System.Data.Linq.Table(Of EmployeeDetail)
		Get
			Return Me.GetTable(Of EmployeeDetail)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EmployeeDetails")>  _
Partial Public Class EmployeeDetail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _EmployeeID As Integer
	
	Private _FirstName As String
	
	Private _MiddleNames As String
	
	Private _LastName As String
	
	Private _DateofBirth As System.Nullable(Of Date)
	
	Private _SexID As System.Nullable(Of Integer)
	
	Private _NINumber As String
	
	Private _Disabilities As String
	
	Private _EmploymentStartDate As System.Nullable(Of Date)
	
	Private _EmploymentTerminated As System.Nullable(Of Boolean)
	
	Private _TerminationDate As System.Nullable(Of Date)
	
	Private _NextReviewDate As System.Nullable(Of Date)
	
	Private _Picture As String
	
	Private _CV As String
	
	Private _MaritalStatusID As System.Nullable(Of Integer)
	
	Private _NextofKin As String
	
	Private _Comments As String
	
	Private _StreetName As String
	
	Private _Address1 As String
	
	Private _Address2 As String
	
	Private _City As String
	
	Private _County As String
	
	Private _PostCode As String
	
	Private _Telephone As String
	
	Private _Mobile As String
	
	Private _Extension As String
	
	Private _Email As String
	
	Private _WorkEmail As String
	
	Private _FullName As String
	
	Private _JobTitle As String
	
	Private _ManagerID As System.Nullable(Of Integer)
	
	Private _HolidayBaseDays As System.Nullable(Of Integer)
	
	Private _LengthofService As System.Nullable(Of Integer)
	
	Private _TotalHolidayDays As System.Nullable(Of Integer)
	
	Private _NickName As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnEmployeeIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnEmployeeIDChanged()
    End Sub
    Partial Private Sub OnFirstNameChanging(value As String)
    End Sub
    Partial Private Sub OnFirstNameChanged()
    End Sub
    Partial Private Sub OnMiddleNamesChanging(value As String)
    End Sub
    Partial Private Sub OnMiddleNamesChanged()
    End Sub
    Partial Private Sub OnLastNameChanging(value As String)
    End Sub
    Partial Private Sub OnLastNameChanged()
    End Sub
    Partial Private Sub OnDateofBirthChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateofBirthChanged()
    End Sub
    Partial Private Sub OnSexIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSexIDChanged()
    End Sub
    Partial Private Sub OnNINumberChanging(value As String)
    End Sub
    Partial Private Sub OnNINumberChanged()
    End Sub
    Partial Private Sub OnDisabilitiesChanging(value As String)
    End Sub
    Partial Private Sub OnDisabilitiesChanged()
    End Sub
    Partial Private Sub OnEmploymentStartDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnEmploymentStartDateChanged()
    End Sub
    Partial Private Sub OnEmploymentTerminatedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnEmploymentTerminatedChanged()
    End Sub
    Partial Private Sub OnTerminationDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnTerminationDateChanged()
    End Sub
    Partial Private Sub OnNextReviewDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnNextReviewDateChanged()
    End Sub
    Partial Private Sub OnPictureChanging(value As String)
    End Sub
    Partial Private Sub OnPictureChanged()
    End Sub
    Partial Private Sub OnCVChanging(value As String)
    End Sub
    Partial Private Sub OnCVChanged()
    End Sub
    Partial Private Sub OnMaritalStatusIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMaritalStatusIDChanged()
    End Sub
    Partial Private Sub OnNextofKinChanging(value As String)
    End Sub
    Partial Private Sub OnNextofKinChanged()
    End Sub
    Partial Private Sub OnCommentsChanging(value As String)
    End Sub
    Partial Private Sub OnCommentsChanged()
    End Sub
    Partial Private Sub OnStreetNameChanging(value As String)
    End Sub
    Partial Private Sub OnStreetNameChanged()
    End Sub
    Partial Private Sub OnAddress1Changing(value As String)
    End Sub
    Partial Private Sub OnAddress1Changed()
    End Sub
    Partial Private Sub OnAddress2Changing(value As String)
    End Sub
    Partial Private Sub OnAddress2Changed()
    End Sub
    Partial Private Sub OnCityChanging(value As String)
    End Sub
    Partial Private Sub OnCityChanged()
    End Sub
    Partial Private Sub OnCountyChanging(value As String)
    End Sub
    Partial Private Sub OnCountyChanged()
    End Sub
    Partial Private Sub OnPostCodeChanging(value As String)
    End Sub
    Partial Private Sub OnPostCodeChanged()
    End Sub
    Partial Private Sub OnTelephoneChanging(value As String)
    End Sub
    Partial Private Sub OnTelephoneChanged()
    End Sub
    Partial Private Sub OnMobileChanging(value As String)
    End Sub
    Partial Private Sub OnMobileChanged()
    End Sub
    Partial Private Sub OnExtensionChanging(value As String)
    End Sub
    Partial Private Sub OnExtensionChanged()
    End Sub
    Partial Private Sub OnEmailChanging(value As String)
    End Sub
    Partial Private Sub OnEmailChanged()
    End Sub
    Partial Private Sub OnWorkEmailChanging(value As String)
    End Sub
    Partial Private Sub OnWorkEmailChanged()
    End Sub
    Partial Private Sub OnFullNameChanging(value As String)
    End Sub
    Partial Private Sub OnFullNameChanged()
    End Sub
    Partial Private Sub OnJobTitleChanging(value As String)
    End Sub
    Partial Private Sub OnJobTitleChanged()
    End Sub
    Partial Private Sub OnManagerIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnManagerIDChanged()
    End Sub
    Partial Private Sub OnHolidayBaseDaysChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnHolidayBaseDaysChanged()
    End Sub
    Partial Private Sub OnLengthofServiceChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLengthofServiceChanged()
    End Sub
    Partial Private Sub OnTotalHolidayDaysChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTotalHolidayDaysChanged()
    End Sub
    Partial Private Sub OnNickNameChanging(value As String)
    End Sub
    Partial Private Sub OnNickNameChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property EmployeeID() As Integer
		Get
			Return Me._EmployeeID
		End Get
		Set
			If ((Me._EmployeeID = value)  _
						= false) Then
				Me.OnEmployeeIDChanging(value)
				Me.SendPropertyChanging
				Me._EmployeeID = value
				Me.SendPropertyChanged("EmployeeID")
				Me.OnEmployeeIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="NVarChar(50)")>  _
	Public Property FirstName() As String
		Get
			Return Me._FirstName
		End Get
		Set
			If (String.Equals(Me._FirstName, value) = false) Then
				Me.OnFirstNameChanging(value)
				Me.SendPropertyChanging
				Me._FirstName = value
				Me.SendPropertyChanged("FirstName")
				Me.OnFirstNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MiddleNames", DbType:="NVarChar(250)")>  _
	Public Property MiddleNames() As String
		Get
			Return Me._MiddleNames
		End Get
		Set
			If (String.Equals(Me._MiddleNames, value) = false) Then
				Me.OnMiddleNamesChanging(value)
				Me.SendPropertyChanging
				Me._MiddleNames = value
				Me.SendPropertyChanged("MiddleNames")
				Me.OnMiddleNamesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="NVarChar(50)")>  _
	Public Property LastName() As String
		Get
			Return Me._LastName
		End Get
		Set
			If (String.Equals(Me._LastName, value) = false) Then
				Me.OnLastNameChanging(value)
				Me.SendPropertyChanging
				Me._LastName = value
				Me.SendPropertyChanged("LastName")
				Me.OnLastNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateofBirth", DbType:="SmallDateTime")>  _
	Public Property DateofBirth() As System.Nullable(Of Date)
		Get
			Return Me._DateofBirth
		End Get
		Set
			If (Me._DateofBirth.Equals(value) = false) Then
				Me.OnDateofBirthChanging(value)
				Me.SendPropertyChanging
				Me._DateofBirth = value
				Me.SendPropertyChanged("DateofBirth")
				Me.OnDateofBirthChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SexID", DbType:="Int")>  _
	Public Property SexID() As System.Nullable(Of Integer)
		Get
			Return Me._SexID
		End Get
		Set
			If (Me._SexID.Equals(value) = false) Then
				Me.OnSexIDChanging(value)
				Me.SendPropertyChanging
				Me._SexID = value
				Me.SendPropertyChanged("SexID")
				Me.OnSexIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NINumber", DbType:="NVarChar(50)")>  _
	Public Property NINumber() As String
		Get
			Return Me._NINumber
		End Get
		Set
			If (String.Equals(Me._NINumber, value) = false) Then
				Me.OnNINumberChanging(value)
				Me.SendPropertyChanging
				Me._NINumber = value
				Me.SendPropertyChanged("NINumber")
				Me.OnNINumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Disabilities", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Disabilities() As String
		Get
			Return Me._Disabilities
		End Get
		Set
			If (String.Equals(Me._Disabilities, value) = false) Then
				Me.OnDisabilitiesChanging(value)
				Me.SendPropertyChanging
				Me._Disabilities = value
				Me.SendPropertyChanged("Disabilities")
				Me.OnDisabilitiesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmploymentStartDate", DbType:="SmallDateTime")>  _
	Public Property EmploymentStartDate() As System.Nullable(Of Date)
		Get
			Return Me._EmploymentStartDate
		End Get
		Set
			If (Me._EmploymentStartDate.Equals(value) = false) Then
				Me.OnEmploymentStartDateChanging(value)
				Me.SendPropertyChanging
				Me._EmploymentStartDate = value
				Me.SendPropertyChanged("EmploymentStartDate")
				Me.OnEmploymentStartDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmploymentTerminated", DbType:="Bit")>  _
	Public Property EmploymentTerminated() As System.Nullable(Of Boolean)
		Get
			Return Me._EmploymentTerminated
		End Get
		Set
			If (Me._EmploymentTerminated.Equals(value) = false) Then
				Me.OnEmploymentTerminatedChanging(value)
				Me.SendPropertyChanging
				Me._EmploymentTerminated = value
				Me.SendPropertyChanged("EmploymentTerminated")
				Me.OnEmploymentTerminatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TerminationDate", DbType:="SmallDateTime")>  _
	Public Property TerminationDate() As System.Nullable(Of Date)
		Get
			Return Me._TerminationDate
		End Get
		Set
			If (Me._TerminationDate.Equals(value) = false) Then
				Me.OnTerminationDateChanging(value)
				Me.SendPropertyChanging
				Me._TerminationDate = value
				Me.SendPropertyChanged("TerminationDate")
				Me.OnTerminationDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NextReviewDate", DbType:="SmallDateTime")>  _
	Public Property NextReviewDate() As System.Nullable(Of Date)
		Get
			Return Me._NextReviewDate
		End Get
		Set
			If (Me._NextReviewDate.Equals(value) = false) Then
				Me.OnNextReviewDateChanging(value)
				Me.SendPropertyChanging
				Me._NextReviewDate = value
				Me.SendPropertyChanged("NextReviewDate")
				Me.OnNextReviewDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Picture", DbType:="VarChar(200)")>  _
	Public Property Picture() As String
		Get
			Return Me._Picture
		End Get
		Set
			If (String.Equals(Me._Picture, value) = false) Then
				Me.OnPictureChanging(value)
				Me.SendPropertyChanging
				Me._Picture = value
				Me.SendPropertyChanged("Picture")
				Me.OnPictureChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CV", DbType:="VarChar(200)")>  _
	Public Property CV() As String
		Get
			Return Me._CV
		End Get
		Set
			If (String.Equals(Me._CV, value) = false) Then
				Me.OnCVChanging(value)
				Me.SendPropertyChanging
				Me._CV = value
				Me.SendPropertyChanged("CV")
				Me.OnCVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaritalStatusID", DbType:="Int")>  _
	Public Property MaritalStatusID() As System.Nullable(Of Integer)
		Get
			Return Me._MaritalStatusID
		End Get
		Set
			If (Me._MaritalStatusID.Equals(value) = false) Then
				Me.OnMaritalStatusIDChanging(value)
				Me.SendPropertyChanging
				Me._MaritalStatusID = value
				Me.SendPropertyChanged("MaritalStatusID")
				Me.OnMaritalStatusIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NextofKin", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property NextofKin() As String
		Get
			Return Me._NextofKin
		End Get
		Set
			If (String.Equals(Me._NextofKin, value) = false) Then
				Me.OnNextofKinChanging(value)
				Me.SendPropertyChanging
				Me._NextofKin = value
				Me.SendPropertyChanged("NextofKin")
				Me.OnNextofKinChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comments", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Comments() As String
		Get
			Return Me._Comments
		End Get
		Set
			If (String.Equals(Me._Comments, value) = false) Then
				Me.OnCommentsChanging(value)
				Me.SendPropertyChanging
				Me._Comments = value
				Me.SendPropertyChanged("Comments")
				Me.OnCommentsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StreetName", DbType:="NVarChar(50)")>  _
	Public Property StreetName() As String
		Get
			Return Me._StreetName
		End Get
		Set
			If (String.Equals(Me._StreetName, value) = false) Then
				Me.OnStreetNameChanging(value)
				Me.SendPropertyChanging
				Me._StreetName = value
				Me.SendPropertyChanged("StreetName")
				Me.OnStreetNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Address1", DbType:="NVarChar(50)")>  _
	Public Property Address1() As String
		Get
			Return Me._Address1
		End Get
		Set
			If (String.Equals(Me._Address1, value) = false) Then
				Me.OnAddress1Changing(value)
				Me.SendPropertyChanging
				Me._Address1 = value
				Me.SendPropertyChanged("Address1")
				Me.OnAddress1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Address2", DbType:="NVarChar(50)")>  _
	Public Property Address2() As String
		Get
			Return Me._Address2
		End Get
		Set
			If (String.Equals(Me._Address2, value) = false) Then
				Me.OnAddress2Changing(value)
				Me.SendPropertyChanging
				Me._Address2 = value
				Me.SendPropertyChanged("Address2")
				Me.OnAddress2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_City", DbType:="NVarChar(50)")>  _
	Public Property City() As String
		Get
			Return Me._City
		End Get
		Set
			If (String.Equals(Me._City, value) = false) Then
				Me.OnCityChanging(value)
				Me.SendPropertyChanging
				Me._City = value
				Me.SendPropertyChanged("City")
				Me.OnCityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_County", DbType:="NVarChar(50)")>  _
	Public Property County() As String
		Get
			Return Me._County
		End Get
		Set
			If (String.Equals(Me._County, value) = false) Then
				Me.OnCountyChanging(value)
				Me.SendPropertyChanging
				Me._County = value
				Me.SendPropertyChanged("County")
				Me.OnCountyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PostCode", DbType:="NChar(10)")>  _
	Public Property PostCode() As String
		Get
			Return Me._PostCode
		End Get
		Set
			If (String.Equals(Me._PostCode, value) = false) Then
				Me.OnPostCodeChanging(value)
				Me.SendPropertyChanging
				Me._PostCode = value
				Me.SendPropertyChanged("PostCode")
				Me.OnPostCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Telephone", DbType:="NVarChar(50)")>  _
	Public Property Telephone() As String
		Get
			Return Me._Telephone
		End Get
		Set
			If (String.Equals(Me._Telephone, value) = false) Then
				Me.OnTelephoneChanging(value)
				Me.SendPropertyChanging
				Me._Telephone = value
				Me.SendPropertyChanged("Telephone")
				Me.OnTelephoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Mobile", DbType:="NVarChar(50)")>  _
	Public Property Mobile() As String
		Get
			Return Me._Mobile
		End Get
		Set
			If (String.Equals(Me._Mobile, value) = false) Then
				Me.OnMobileChanging(value)
				Me.SendPropertyChanging
				Me._Mobile = value
				Me.SendPropertyChanged("Mobile")
				Me.OnMobileChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Extension", DbType:="NVarChar(50)")>  _
	Public Property Extension() As String
		Get
			Return Me._Extension
		End Get
		Set
			If (String.Equals(Me._Extension, value) = false) Then
				Me.OnExtensionChanging(value)
				Me.SendPropertyChanging
				Me._Extension = value
				Me.SendPropertyChanged("Extension")
				Me.OnExtensionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="NVarChar(50)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me.OnEmailChanging(value)
				Me.SendPropertyChanging
				Me._Email = value
				Me.SendPropertyChanged("Email")
				Me.OnEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorkEmail", DbType:="NVarChar(50)")>  _
	Public Property WorkEmail() As String
		Get
			Return Me._WorkEmail
		End Get
		Set
			If (String.Equals(Me._WorkEmail, value) = false) Then
				Me.OnWorkEmailChanging(value)
				Me.SendPropertyChanging
				Me._WorkEmail = value
				Me.SendPropertyChanged("WorkEmail")
				Me.OnWorkEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullName", AutoSync:=AutoSync.Always, DbType:="NVarChar(101)", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property FullName() As String
		Get
			Return Me._FullName
		End Get
		Set
			If (String.Equals(Me._FullName, value) = false) Then
				Me.OnFullNameChanging(value)
				Me.SendPropertyChanging
				Me._FullName = value
				Me.SendPropertyChanged("FullName")
				Me.OnFullNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_JobTitle", DbType:="NVarChar(50)")>  _
	Public Property JobTitle() As String
		Get
			Return Me._JobTitle
		End Get
		Set
			If (String.Equals(Me._JobTitle, value) = false) Then
				Me.OnJobTitleChanging(value)
				Me.SendPropertyChanging
				Me._JobTitle = value
				Me.SendPropertyChanged("JobTitle")
				Me.OnJobTitleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ManagerID", DbType:="Int")>  _
	Public Property ManagerID() As System.Nullable(Of Integer)
		Get
			Return Me._ManagerID
		End Get
		Set
			If (Me._ManagerID.Equals(value) = false) Then
				Me.OnManagerIDChanging(value)
				Me.SendPropertyChanging
				Me._ManagerID = value
				Me.SendPropertyChanged("ManagerID")
				Me.OnManagerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HolidayBaseDays", DbType:="Int")>  _
	Public Property HolidayBaseDays() As System.Nullable(Of Integer)
		Get
			Return Me._HolidayBaseDays
		End Get
		Set
			If (Me._HolidayBaseDays.Equals(value) = false) Then
				Me.OnHolidayBaseDaysChanging(value)
				Me.SendPropertyChanging
				Me._HolidayBaseDays = value
				Me.SendPropertyChanged("HolidayBaseDays")
				Me.OnHolidayBaseDaysChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LengthofService", AutoSync:=AutoSync.Always, DbType:="Int", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property LengthofService() As System.Nullable(Of Integer)
		Get
			Return Me._LengthofService
		End Get
		Set
			If (Me._LengthofService.Equals(value) = false) Then
				Me.OnLengthofServiceChanging(value)
				Me.SendPropertyChanging
				Me._LengthofService = value
				Me.SendPropertyChanged("LengthofService")
				Me.OnLengthofServiceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalHolidayDays", AutoSync:=AutoSync.Always, DbType:="Int", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property TotalHolidayDays() As System.Nullable(Of Integer)
		Get
			Return Me._TotalHolidayDays
		End Get
		Set
			If (Me._TotalHolidayDays.Equals(value) = false) Then
				Me.OnTotalHolidayDaysChanging(value)
				Me.SendPropertyChanging
				Me._TotalHolidayDays = value
				Me.SendPropertyChanged("TotalHolidayDays")
				Me.OnTotalHolidayDaysChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NickName", DbType:="NVarChar(50)")>  _
	Public Property NickName() As String
		Get
			Return Me._NickName
		End Get
		Set
			If (String.Equals(Me._NickName, value) = false) Then
				Me.OnNickNameChanging(value)
				Me.SendPropertyChanging
				Me._NickName = value
				Me.SendPropertyChanged("NickName")
				Me.OnNickNameChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
