'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="support")>  _
Partial Public Class TechnicalDataClassesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertOrganisationDetail(instance As OrganisationDetail)
    End Sub
  Partial Private Sub UpdateOrganisationDetail(instance As OrganisationDetail)
    End Sub
  Partial Private Sub DeleteOrganisationDetail(instance As OrganisationDetail)
    End Sub
  Partial Private Sub InsertDevice(instance As Device)
    End Sub
  Partial Private Sub UpdateDevice(instance As Device)
    End Sub
  Partial Private Sub DeleteDevice(instance As Device)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("supportConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property OrganisationDetails() As System.Data.Linq.Table(Of OrganisationDetail)
		Get
			Return Me.GetTable(Of OrganisationDetail)
		End Get
	End Property
	
	Public ReadOnly Property SelectOrganisationIDByEmployeeIDViews() As System.Data.Linq.Table(Of SelectOrganisationIDByEmployeeIDView)
		Get
			Return Me.GetTable(Of SelectOrganisationIDByEmployeeIDView)
		End Get
	End Property
	
	Public ReadOnly Property Devices() As System.Data.Linq.Table(Of Device)
		Get
			Return Me.GetTable(Of Device)
		End Get
	End Property
	
	Public ReadOnly Property DeviceOrganisationSiteParentViews() As System.Data.Linq.Table(Of DeviceOrganisationSiteParentView)
		Get
			Return Me.GetTable(Of DeviceOrganisationSiteParentView)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.OrganisationDetails")>  _
Partial Public Class OrganisationDetail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrganisationID As Integer
	
	Private _AccountIdName As String
	
	Private _OrganisationDescription As String
	
	Private _Inactive As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrganisationIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnOrganisationIDChanged()
    End Sub
    Partial Private Sub OnAccountIdNameChanging(value As String)
    End Sub
    Partial Private Sub OnAccountIdNameChanged()
    End Sub
    Partial Private Sub OnOrganisationDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnOrganisationDescriptionChanged()
    End Sub
    Partial Private Sub OnInactiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnInactiveChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrganisationID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property OrganisationID() As Integer
		Get
			Return Me._OrganisationID
		End Get
		Set
			If ((Me._OrganisationID = value)  _
						= false) Then
				Me.OnOrganisationIDChanging(value)
				Me.SendPropertyChanging
				Me._OrganisationID = value
				Me.SendPropertyChanged("OrganisationID")
				Me.OnOrganisationIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountIdName", DbType:="NVarChar(50)")>  _
	Public Property AccountIdName() As String
		Get
			Return Me._AccountIdName
		End Get
		Set
			If (String.Equals(Me._AccountIdName, value) = false) Then
				Me.OnAccountIdNameChanging(value)
				Me.SendPropertyChanging
				Me._AccountIdName = value
				Me.SendPropertyChanged("AccountIdName")
				Me.OnAccountIdNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrganisationDescription", DbType:="NVarChar(MAX)")>  _
	Public Property OrganisationDescription() As String
		Get
			Return Me._OrganisationDescription
		End Get
		Set
			If (String.Equals(Me._OrganisationDescription, value) = false) Then
				Me.OnOrganisationDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._OrganisationDescription = value
				Me.SendPropertyChanged("OrganisationDescription")
				Me.OnOrganisationDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Inactive", DbType:="Bit")>  _
	Public Property Inactive() As System.Nullable(Of Boolean)
		Get
			Return Me._Inactive
		End Get
		Set
			If (Me._Inactive.Equals(value) = false) Then
				Me.OnInactiveChanging(value)
				Me.SendPropertyChanging
				Me._Inactive = value
				Me.SendPropertyChanged("Inactive")
				Me.OnInactiveChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SelectOrganisationIDByEmployeeIDView")>  _
Partial Public Class SelectOrganisationIDByEmployeeIDView
	
	Private _OrganisationID As Integer
	
	Private _AccountIdName As String
	
	Private _EmployeeID As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrganisationID", DbType:="Int NOT NULL")>  _
	Public Property OrganisationID() As Integer
		Get
			Return Me._OrganisationID
		End Get
		Set
			If ((Me._OrganisationID = value)  _
						= false) Then
				Me._OrganisationID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountIdName", DbType:="NVarChar(50)")>  _
	Public Property AccountIdName() As String
		Get
			Return Me._AccountIdName
		End Get
		Set
			If (String.Equals(Me._AccountIdName, value) = false) Then
				Me._AccountIdName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeID", DbType:="Int NOT NULL")>  _
	Public Property EmployeeID() As Integer
		Get
			Return Me._EmployeeID
		End Get
		Set
			If ((Me._EmployeeID = value)  _
						= false) Then
				Me._EmployeeID = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Device")>  _
Partial Public Class Device
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _DeviceID As Integer
	
	Private _ModelNumber As String
	
	Private _SerialNumber As String
	
	Private _Specification As String
	
	Private _DeviceStatusID As Integer
	
	Private _DeviceTypeID As System.Nullable(Of Integer)
	
	Private _ParentDeviceID As Integer
	
	Private _ExternalSubnetID As System.Nullable(Of Integer)
	
	Private _InternalSubnetID As System.Nullable(Of Integer)
	
	Private _SiteID As System.Nullable(Of Integer)
	
	Private _ExternalIP As String
	
	Private _InternalIP As String
	
	Private _HostName As String
	
	Private _DeviceDescription As String
	
	Private _Comments As String
	
	Private _OperatingSystemID As Integer
	
	Private _ThirdPartyDetails As String
	
	Private _Active As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDeviceIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnDeviceIDChanged()
    End Sub
    Partial Private Sub OnModelNumberChanging(value As String)
    End Sub
    Partial Private Sub OnModelNumberChanged()
    End Sub
    Partial Private Sub OnSerialNumberChanging(value As String)
    End Sub
    Partial Private Sub OnSerialNumberChanged()
    End Sub
    Partial Private Sub OnSpecificationChanging(value As String)
    End Sub
    Partial Private Sub OnSpecificationChanged()
    End Sub
    Partial Private Sub OnDeviceStatusIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnDeviceStatusIDChanged()
    End Sub
    Partial Private Sub OnDeviceTypeIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDeviceTypeIDChanged()
    End Sub
    Partial Private Sub OnParentDeviceIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnParentDeviceIDChanged()
    End Sub
    Partial Private Sub OnExternalSubnetIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnExternalSubnetIDChanged()
    End Sub
    Partial Private Sub OnInternalSubnetIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnInternalSubnetIDChanged()
    End Sub
    Partial Private Sub OnSiteIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSiteIDChanged()
    End Sub
    Partial Private Sub OnExternalIPChanging(value As String)
    End Sub
    Partial Private Sub OnExternalIPChanged()
    End Sub
    Partial Private Sub OnInternalIPChanging(value As String)
    End Sub
    Partial Private Sub OnInternalIPChanged()
    End Sub
    Partial Private Sub OnHostNameChanging(value As String)
    End Sub
    Partial Private Sub OnHostNameChanged()
    End Sub
    Partial Private Sub OnDeviceDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnDeviceDescriptionChanged()
    End Sub
    Partial Private Sub OnCommentsChanging(value As String)
    End Sub
    Partial Private Sub OnCommentsChanged()
    End Sub
    Partial Private Sub OnOperatingSystemIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnOperatingSystemIDChanged()
    End Sub
    Partial Private Sub OnThirdPartyDetailsChanging(value As String)
    End Sub
    Partial Private Sub OnThirdPartyDetailsChanged()
    End Sub
    Partial Private Sub OnActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnActiveChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property DeviceID() As Integer
		Get
			Return Me._DeviceID
		End Get
		Set
			If ((Me._DeviceID = value)  _
						= false) Then
				Me.OnDeviceIDChanging(value)
				Me.SendPropertyChanging
				Me._DeviceID = value
				Me.SendPropertyChanged("DeviceID")
				Me.OnDeviceIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModelNumber", DbType:="NVarChar(50)")>  _
	Public Property ModelNumber() As String
		Get
			Return Me._ModelNumber
		End Get
		Set
			If (String.Equals(Me._ModelNumber, value) = false) Then
				Me.OnModelNumberChanging(value)
				Me.SendPropertyChanging
				Me._ModelNumber = value
				Me.SendPropertyChanged("ModelNumber")
				Me.OnModelNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SerialNumber", DbType:="NVarChar(50)")>  _
	Public Property SerialNumber() As String
		Get
			Return Me._SerialNumber
		End Get
		Set
			If (String.Equals(Me._SerialNumber, value) = false) Then
				Me.OnSerialNumberChanging(value)
				Me.SendPropertyChanging
				Me._SerialNumber = value
				Me.SendPropertyChanged("SerialNumber")
				Me.OnSerialNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Specification", DbType:="NVarChar(MAX)")>  _
	Public Property Specification() As String
		Get
			Return Me._Specification
		End Get
		Set
			If (String.Equals(Me._Specification, value) = false) Then
				Me.OnSpecificationChanging(value)
				Me.SendPropertyChanging
				Me._Specification = value
				Me.SendPropertyChanged("Specification")
				Me.OnSpecificationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceStatusID", DbType:="Int NOT NULL")>  _
	Public Property DeviceStatusID() As Integer
		Get
			Return Me._DeviceStatusID
		End Get
		Set
			If ((Me._DeviceStatusID = value)  _
						= false) Then
				Me.OnDeviceStatusIDChanging(value)
				Me.SendPropertyChanging
				Me._DeviceStatusID = value
				Me.SendPropertyChanged("DeviceStatusID")
				Me.OnDeviceStatusIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceTypeID", DbType:="Int")>  _
	Public Property DeviceTypeID() As System.Nullable(Of Integer)
		Get
			Return Me._DeviceTypeID
		End Get
		Set
			If (Me._DeviceTypeID.Equals(value) = false) Then
				Me.OnDeviceTypeIDChanging(value)
				Me.SendPropertyChanging
				Me._DeviceTypeID = value
				Me.SendPropertyChanged("DeviceTypeID")
				Me.OnDeviceTypeIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ParentDeviceID", DbType:="Int NOT NULL")>  _
	Public Property ParentDeviceID() As Integer
		Get
			Return Me._ParentDeviceID
		End Get
		Set
			If ((Me._ParentDeviceID = value)  _
						= false) Then
				Me.OnParentDeviceIDChanging(value)
				Me.SendPropertyChanging
				Me._ParentDeviceID = value
				Me.SendPropertyChanged("ParentDeviceID")
				Me.OnParentDeviceIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExternalSubnetID", DbType:="Int")>  _
	Public Property ExternalSubnetID() As System.Nullable(Of Integer)
		Get
			Return Me._ExternalSubnetID
		End Get
		Set
			If (Me._ExternalSubnetID.Equals(value) = false) Then
				Me.OnExternalSubnetIDChanging(value)
				Me.SendPropertyChanging
				Me._ExternalSubnetID = value
				Me.SendPropertyChanged("ExternalSubnetID")
				Me.OnExternalSubnetIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InternalSubnetID", DbType:="Int")>  _
	Public Property InternalSubnetID() As System.Nullable(Of Integer)
		Get
			Return Me._InternalSubnetID
		End Get
		Set
			If (Me._InternalSubnetID.Equals(value) = false) Then
				Me.OnInternalSubnetIDChanging(value)
				Me.SendPropertyChanging
				Me._InternalSubnetID = value
				Me.SendPropertyChanged("InternalSubnetID")
				Me.OnInternalSubnetIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SiteID", DbType:="Int")>  _
	Public Property SiteID() As System.Nullable(Of Integer)
		Get
			Return Me._SiteID
		End Get
		Set
			If (Me._SiteID.Equals(value) = false) Then
				Me.OnSiteIDChanging(value)
				Me.SendPropertyChanging
				Me._SiteID = value
				Me.SendPropertyChanged("SiteID")
				Me.OnSiteIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExternalIP", DbType:="NChar(15)")>  _
	Public Property ExternalIP() As String
		Get
			Return Me._ExternalIP
		End Get
		Set
			If (String.Equals(Me._ExternalIP, value) = false) Then
				Me.OnExternalIPChanging(value)
				Me.SendPropertyChanging
				Me._ExternalIP = value
				Me.SendPropertyChanged("ExternalIP")
				Me.OnExternalIPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InternalIP", DbType:="NChar(15)")>  _
	Public Property InternalIP() As String
		Get
			Return Me._InternalIP
		End Get
		Set
			If (String.Equals(Me._InternalIP, value) = false) Then
				Me.OnInternalIPChanging(value)
				Me.SendPropertyChanging
				Me._InternalIP = value
				Me.SendPropertyChanged("InternalIP")
				Me.OnInternalIPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HostName", DbType:="NVarChar(50)")>  _
	Public Property HostName() As String
		Get
			Return Me._HostName
		End Get
		Set
			If (String.Equals(Me._HostName, value) = false) Then
				Me.OnHostNameChanging(value)
				Me.SendPropertyChanging
				Me._HostName = value
				Me.SendPropertyChanged("HostName")
				Me.OnHostNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceDescription", DbType:="NVarChar(MAX)")>  _
	Public Property DeviceDescription() As String
		Get
			Return Me._DeviceDescription
		End Get
		Set
			If (String.Equals(Me._DeviceDescription, value) = false) Then
				Me.OnDeviceDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._DeviceDescription = value
				Me.SendPropertyChanged("DeviceDescription")
				Me.OnDeviceDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comments", DbType:="NVarChar(MAX)")>  _
	Public Property Comments() As String
		Get
			Return Me._Comments
		End Get
		Set
			If (String.Equals(Me._Comments, value) = false) Then
				Me.OnCommentsChanging(value)
				Me.SendPropertyChanging
				Me._Comments = value
				Me.SendPropertyChanged("Comments")
				Me.OnCommentsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OperatingSystemID", DbType:="Int NOT NULL")>  _
	Public Property OperatingSystemID() As Integer
		Get
			Return Me._OperatingSystemID
		End Get
		Set
			If ((Me._OperatingSystemID = value)  _
						= false) Then
				Me.OnOperatingSystemIDChanging(value)
				Me.SendPropertyChanging
				Me._OperatingSystemID = value
				Me.SendPropertyChanged("OperatingSystemID")
				Me.OnOperatingSystemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThirdPartyDetails", DbType:="NVarChar(MAX)")>  _
	Public Property ThirdPartyDetails() As String
		Get
			Return Me._ThirdPartyDetails
		End Get
		Set
			If (String.Equals(Me._ThirdPartyDetails, value) = false) Then
				Me.OnThirdPartyDetailsChanging(value)
				Me.SendPropertyChanging
				Me._ThirdPartyDetails = value
				Me.SendPropertyChanged("ThirdPartyDetails")
				Me.OnThirdPartyDetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Active", DbType:="Bit")>  _
	Public Property Active() As System.Nullable(Of Boolean)
		Get
			Return Me._Active
		End Get
		Set
			If (Me._Active.Equals(value) = false) Then
				Me.OnActiveChanging(value)
				Me.SendPropertyChanging
				Me._Active = value
				Me.SendPropertyChanged("Active")
				Me.OnActiveChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.DeviceOrganisationSiteParentView")>  _
Partial Public Class DeviceOrganisationSiteParentView
	
	Private _ModelNumber As String
	
	Private _SerialNumber As String
	
	Private _ThirdPartyDetails As String
	
	Private _Specification As String
	
	Private _Comments As String
	
	Private _Active As System.Nullable(Of Boolean)
	
	Private _HostName As String
	
	Private _SiteName As String
	
	Private _ParentDeviceID As Integer
	
	Private _OrganisationID As System.Nullable(Of Integer)
	
	Private _DeviceStatusID As Integer
	
	Private _ParentHostName As String
	
	Private _DeviceStatus As String
	
	Private _DeviceID As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModelNumber", DbType:="NVarChar(50)")>  _
	Public Property ModelNumber() As String
		Get
			Return Me._ModelNumber
		End Get
		Set
			If (String.Equals(Me._ModelNumber, value) = false) Then
				Me._ModelNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SerialNumber", DbType:="NVarChar(50)")>  _
	Public Property SerialNumber() As String
		Get
			Return Me._SerialNumber
		End Get
		Set
			If (String.Equals(Me._SerialNumber, value) = false) Then
				Me._SerialNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThirdPartyDetails", DbType:="NVarChar(MAX)")>  _
	Public Property ThirdPartyDetails() As String
		Get
			Return Me._ThirdPartyDetails
		End Get
		Set
			If (String.Equals(Me._ThirdPartyDetails, value) = false) Then
				Me._ThirdPartyDetails = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Specification", DbType:="NVarChar(MAX)")>  _
	Public Property Specification() As String
		Get
			Return Me._Specification
		End Get
		Set
			If (String.Equals(Me._Specification, value) = false) Then
				Me._Specification = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comments", DbType:="NVarChar(MAX)")>  _
	Public Property Comments() As String
		Get
			Return Me._Comments
		End Get
		Set
			If (String.Equals(Me._Comments, value) = false) Then
				Me._Comments = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Active", DbType:="Bit")>  _
	Public Property Active() As System.Nullable(Of Boolean)
		Get
			Return Me._Active
		End Get
		Set
			If (Me._Active.Equals(value) = false) Then
				Me._Active = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HostName", DbType:="NVarChar(50)")>  _
	Public Property HostName() As String
		Get
			Return Me._HostName
		End Get
		Set
			If (String.Equals(Me._HostName, value) = false) Then
				Me._HostName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SiteName", DbType:="NVarChar(150)")>  _
	Public Property SiteName() As String
		Get
			Return Me._SiteName
		End Get
		Set
			If (String.Equals(Me._SiteName, value) = false) Then
				Me._SiteName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ParentDeviceID", DbType:="Int NOT NULL")>  _
	Public Property ParentDeviceID() As Integer
		Get
			Return Me._ParentDeviceID
		End Get
		Set
			If ((Me._ParentDeviceID = value)  _
						= false) Then
				Me._ParentDeviceID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrganisationID", DbType:="Int")>  _
	Public Property OrganisationID() As System.Nullable(Of Integer)
		Get
			Return Me._OrganisationID
		End Get
		Set
			If (Me._OrganisationID.Equals(value) = false) Then
				Me._OrganisationID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceStatusID", DbType:="Int NOT NULL")>  _
	Public Property DeviceStatusID() As Integer
		Get
			Return Me._DeviceStatusID
		End Get
		Set
			If ((Me._DeviceStatusID = value)  _
						= false) Then
				Me._DeviceStatusID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ParentHostName", DbType:="NVarChar(50)")>  _
	Public Property ParentHostName() As String
		Get
			Return Me._ParentHostName
		End Get
		Set
			If (String.Equals(Me._ParentHostName, value) = false) Then
				Me._ParentHostName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceStatus", DbType:="NVarChar(50)")>  _
	Public Property DeviceStatus() As String
		Get
			Return Me._DeviceStatus
		End Get
		Set
			If (String.Equals(Me._DeviceStatus, value) = false) Then
				Me._DeviceStatus = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeviceID", DbType:="Int NOT NULL")>  _
	Public Property DeviceID() As Integer
		Get
			Return Me._DeviceID
		End Get
		Set
			If ((Me._DeviceID = value)  _
						= false) Then
				Me._DeviceID = value
			End If
		End Set
	End Property
End Class
